### ISSUE TITLE
Confirm Form Resubmission

### ISSUE THREAD

**Issue by iamapuneet** [LearnCodeWithDurgesh/scm2.0#1]
![image](https://github.com/LearnCodeWithDurgesh/scm2.0/assets/108384826/45cdcee2-b952-436e-858f-a906ad3ee2be)

Jab  Hum Thymeleaf me Post Method ka use karte hai tab . Confirm From Resubmission ka Pop up ata hai. isko kaise remove kare make new video . Please Make New Video For This issue.

Thanks.

**Comment by LearnCodeWithDurgesh** [comment]
Explain your flow.  where you are using post method?  we have used post method in project many times but not got any. such message.

**Comment by iamapuneet** [comment]
> Explain your flow. where you are using post method? we have used post method in project many times but not got any. such message.
Plese Check :- https://screenrec.com/share/FHe0zdUEJw
 
<img width="889" alt="image" src="https://github.com/LearnCodeWithDurgesh/scm2.0/assets/108384826/d35a12b5-edb2-49d5-94b6-dc8b5d8a8cfd">

**Comment by azan-baloch** [comment]
This is not a problem; this is how the browser acts when you use the POST method. To avoid this popup while getting a validation error, you can redirect the user to the GET method, e.g., return "redirect:signup"

**Comment by Mohitpatel021** [comment]
To avoid this problem You can follow the PRG approch for better experience.You can redirect to any other GET method URL .
